<template>
  <main id="top">
    <section class="hero"><ParticlesCanvas /><div class="hero-grid"><div class="hero-copy"><p class="eyebrow">DATA × IA × LOGICIEL</p><h1>KOUAME JUDE<br><em>SAMSON TANOH</em></h1><p class="hero-focus">DATA ANALYST <i>&</i> DATA SCIENTIST</p><p class="hero-role">Analyse de données · Data Science · Machine Learning · IA · Full-Stack</p><p class="hero-statement">Je transforme les données en <strong>insights, modèles et applications.</strong></p><div class="hero-actions"><a class="button primary" href="#projects">Découvrir mes projets <b>↓</b></a><a class="button ghost" href="/CV_KOUAME_JUDE_SAMSON_TANOH.pdf" target="_blank">Télécharger mon CV <b>↗</b></a></div><div class="socials"><a href="https://github.com" target="_blank">GitHub ↗</a><a href="https://www.linkedin.com/in/jude-samson-tanoh-kouame-76032a38b/" target="_blank">LinkedIn ↗</a><a href="mailto:samson.kouame@epitech.eu">E-mail ↗</a></div></div><aside class="hero-panel"><img src="/photo.jpg" alt="Portrait de Kouame Jude Samson Tanoh"><div class="panel-readout"><span>01 / LABORATOIRE D'INTELLIGENCE DATA</span><strong>Donnée → insight → impact</strong></div><div class="signal one"></div><div class="signal two"></div></aside></div></section>
    <section id="about" class="section about"><p class="eyebrow">01 / À PROPOS</p><div class="split-heading"><h2>LA DATA EST MON<br><em>POINT DE DÉPART.</em></h2><p>Je travaille à l’intersection de la Data, de l’Intelligence Artificielle et du développement logiciel — de l’exploration à l’application.</p></div><div class="data-chain"><span>DONNÉES</span><i></i><span>ANALYSE</span><i></i><span>INSIGHTS</span><i></i><span>ML / IA</span><i></i><span>APPLICATIONS</span></div><div class="disciplines"><article v-for="(item, index) in disciplines" :key="item.title"><span>0{{ index + 1 }}</span><h3>{{ item.title }}</h3><p>{{ item.text }}</p></article></div></section>
    <section id="skills" class="section skills"><p class="eyebrow">02 / COMPÉTENCES</p><div class="split-heading"><h2>De la donnée brute<br>au <em>produit utile.</em></h2><p>Une pratique orientée données, IA et ingénierie.</p></div><div class="skill-grid"><article v-for="group in skills" :key="group.title" class="skill-group"><div><span>{{ group.id }}</span><h3>{{ group.title }}</h3></div><div class="tags"><b v-for="tag in group.tags" :key="tag">{{ tag }}</b></div></article></div></section>
    <section id="projects" class="section projects"><p class="eyebrow">03 / ÉTUDES DE CAS SÉLECTIONNÉES</p><div class="projects-intro"><div><h2>Les projets sont<br>la <em>preuve.</em></h2><p>Des systèmes conçus pour explorer, modéliser et rendre les résultats utilisables.</p></div><div class="filters"><button v-for="filter in filters" :key="filter" :class="{ active: activeFilter === filter }" @click="activeFilter = filter">{{ filter }}</button></div></div><div class="project-grid"><article v-for="project in filteredProjects" :key="project.title" class="project-card" @click="selected = project"><div :class="['project-visual', project.visual]"><span>{{ project.number }}</span><div v-if="project.visual === 'pipeline'" class="mini-pipeline"><b>API</b><i>→</i><b>KAFKA</b><i>→</i><b>ML</b><i>→</i><b>DB</b></div><div v-else class="visual-mark">{{ project.mark }}</div></div><div class="project-content"><div class="project-meta"><span>{{ project.category }}</span><span>2026</span></div><h3>{{ project.title }}</h3><p>{{ project.summary }}</p><div class="tags"><b v-for="tag in project.tags.slice(0, 3)" :key="tag">{{ tag }}</b></div><button class="text-link">Voir l'étude de cas <span>↗</span></button></div></article></div></section>
    <section id="process" class="section build"><p class="eyebrow">04 / DE LA DONNÉE AU PRODUIT</p><h2>Une méthode qui relie<br>rigueur et livraison.</h2><div class="build-track"><article v-for="(step, index) in buildSteps" :key="step"><span>0{{ index + 1 }}</span><strong>{{ step }}</strong><i></i></article></div></section>
    <Certifications />
    <section id="experience" class="section experience"><p class="eyebrow">06 / FORMATION</p><div class="experience-card"><span class="period">PARCOURS ACADÉMIQUE</span><div><h2>Informatique et<br>Sciences du Numérique</h2><p>UVCI — Université Virtuelle de Côte d’Ivoire</p></div><span class="status"><i></i> EN FORMATION</span></div></section>
    <section id="contact" class="contact"><div><p class="eyebrow">07 / CONTACT</p><h2>CONSTRUISONS AVEC<br>LA <em>DATA.</em></h2><p class="contact-copy">Disponible pour des stages et des opportunités junior en Data, IA et ingénierie logicielle.</p><div class="contact-links"><a href="mailto:samson.kouame@epitech.eu">samson.kouame@epitech.eu</a><a href="https://www.linkedin.com/in/jude-samson-tanoh-kouame-76032a38b/" target="_blank">LinkedIn ↗</a><a href="https://github.com" target="_blank">GitHub ↗</a></div></div><form @submit.prevent="sendMessage"><label>Nom<input v-model="form.name" required></label><label>E-mail<input v-model="form.email" type="email" required></label><label>Message<textarea v-model="form.message" rows="4" required></textarea></label><button class="button primary">Envoyer le message <b>↗</b></button></form></section>
  </main>
  <footer><span>SAMSON TANOH</span><span>DATA ANALYST · DATA SCIENTIST · IA · LOGICIEL</span><span>© 2026</span></footer>
  <div v-if="selected" class="modal" role="dialog" aria-modal="true" @click.self="selected = null"><article><button class="close" @click="selected = null" aria-label="Fermer">×</button><p class="eyebrow">PROJET / {{ selected.category }}</p><h2>{{ selected.title }}</h2><div class="modal-grid"><div><h3>LE PROBLÈME</h3><p>{{ selected.problem }}</p></div><div><h3>L’APPROCHE</h3><p>{{ selected.approach }}</p></div><div><h3>ARCHITECTURE</h3><p class="architecture">{{ selected.architecture || selected.approach }}</p></div><div><h3>RÉSULTATS ET IMPACT</h3><p>{{ selected.results }}</p></div><div><h3>STACK TECHNIQUE</h3><div class="tags"><b v-for="tag in selected.tags" :key="tag">{{ tag }}</b></div></div></div><a v-if="selected.demo" :href="selected.demo" target="_blank" class="button ghost">{{ selected.demoLabel || 'Démo en ligne ↗' }}</a></article></div>
</template>

<script setup>
import { computed, reactive, ref } from 'vue'
import ParticlesCanvas from '../components/ParticlesCanvas.vue'
import Certifications from '../components/Certifications.vue'

const disciplines = [
  { title: 'Analyse de données', text: 'Explorer, nettoyer et visualiser les données pour faire émerger des insights exploitables.' },
  { title: 'Data Science', text: 'Construire des modèles prédictifs et des pipelines de Machine Learning.' },
  { title: 'IA / Machine Learning', text: 'Travailler sur la classification, le NLP et le Deep Learning.' },
  { title: 'Ingénierie logicielle', text: 'Transformer les solutions data en applications web exploitables.' }
]
const skills = [
  { id: '01', title: 'ANALYSE DE DONNÉES', tags: ['Python', 'Pandas', 'NumPy', 'Seaborn', 'Matplotlib', 'EDA', 'Nettoyage des données', 'Visualisation de données', 'Power BI', 'Tableaux de bord'] },
  { id: '02', title: 'DATA SCIENCE', tags: ['scikit-learn', 'Machine Learning', 'Statistiques', 'Modélisation prédictive'] },
  { id: '03', title: 'IA / NLP', tags: ['TensorFlow', 'Deep Learning', 'NLP', 'Classification de texte'] },
  { id: '04', title: 'INGÉNIERIE DES DONNÉES', tags: ['SQL', 'PostgreSQL', 'Apache Kafka', 'Docker', 'ETL', 'Pipelines de données'] },
  { id: '05', title: 'INGÉNIERIE LOGICIELLE', tags: ['Laravel', 'PHP', 'Vue.js', 'JavaScript', 'REST API'] }
]
const filters = ['TOUT', 'ANALYSE DE DONNÉES', 'DATA SCIENCE', 'IA / ML', 'INGÉNIERIE DES DONNÉES', 'WEB']
const activeFilter = ref('TOUT')
const selected = ref(null)
const projects = [
  { number: '01', category: 'INGÉNIERIE DES DONNÉES', title: 'Sentiment Analysis Pipeline', summary: 'Un pipeline temps réel qui transforme les commentaires de films en décisions mesurables.', tags: ['Python', 'Kafka', 'scikit-learn', 'LinearSVC', 'PostgreSQL', 'Docker'], visual: 'pipeline', problem: 'Qualifier automatiquement de grands volumes de commentaires de films.', approach: 'Commentaires de films → Kafka → LinearSVC → classification → PostgreSQL → tableau de bord.', architecture: 'COMMENTAIRES DE FILMS → KAFKA → LINEARSVC → CLASSIFICATION → POSTGRESQL → TABLEAU DE BORD', results: 'Précision ≈ 89 % sur environ 50 000 commentaires.' },
  { number: '02', category: 'DATA SCIENCE', title: 'Malaria & Climate Data', summary: 'Le lien entre climat et cas de paludisme en Côte d’Ivoire.', tags: ['Python', 'Analyse de données', 'Régression', 'Visualisation de données'], visual: 'climate', mark: 'R² .866', problem: 'Étudier l’influence des variables climatiques sur les cas de paludisme.', approach: 'Analyse des données 2000–2024 : température, humidité, précipitations et vent.', results: 'R² ≈ 0,866, avec un ancrage direct dans le contexte ivoirien.' },
  { number: '03', category: 'ANALYSE DE DONNÉES', title: 'Exploratory Data Analysis', summary: 'Des données brutes aux insights : comprendre un dataset avant de décider.', tags: ['Python', 'Pandas', 'Seaborn', 'Power BI'], visual: 'eda', mark: 'EDA', problem: 'Comprendre la structure, les tendances et anomalies d’un dataset afin d’en tirer des insights utiles.', approach: 'Compréhension → exploration → nettoyage → analyse statistique → tendances → visualisation → tableau de bord → interprétation.', architecture: 'DATASET → COMPRÉHENSION → NETTOYAGE → EDA → VISUALISATION → INSIGHTS → TABLEAU DE BORD', results: 'Un dataset brut devient une compréhension exploitable grâce à Python, à la visualisation et à Power BI.', demo: 'https://lnkd.in/p/dbGD5Pm9', demoLabel: 'Voir la publication LinkedIn ↗' },
  { number: '04', category: 'IA / ML', title: 'Book Recommendation System', summary: 'Un moteur NLP de recommandation de livres.', tags: ['Python', 'Bag of Words', 'TF-IDF', 'TruncatedSVD', 'Cosine Similarity'], visual: 'books', mark: 'TF·IDF', problem: 'Aider un lecteur à découvrir des ouvrages proches de ses intérêts.', approach: '50 livres → Bag of Words → TF-IDF → SVD → Cosine Similarity.', results: 'Un moteur de recommandation basé sur la proximité sémantique.' },
  { number: '05', category: 'WEB', title: 'YOWL', summary: 'Plateforme de centralisation et de commentaire de contenus en ligne.', tags: ['Vue.js', 'Laravel', 'Inertia', 'CRUD', 'Gestion des utilisateurs'], visual: 'yowl', mark: 'API', problem: 'Centraliser du contenu en ligne et permettre son commentaire.', approach: 'Vue.js → Laravel → base de données.', results: 'Une architecture Full-Stack orientée interactions et contenu.' },
  { number: '06', category: 'WEB', title: 'FreeAds', summary: 'Publication et gestion d’annonces.', tags: ['Laravel', 'PHP', 'Base de données', 'Authentification', 'CRUD'], visual: 'ads', mark: 'CRUD', problem: 'Rendre la publication et la gestion d’annonces simple.', approach: 'Application Laravel avec authentification et CRUD.', results: 'Une base complète pour publier, consulter et administrer.' },
  { number: '07', category: 'WEB', title: 'MyShop', summary: 'Application e-commerce et gestion de produits en PHP.', tags: ['PHP', 'OOP', 'PDO', 'MySQL'], visual: 'shop', mark: 'OOP', problem: 'Construire un catalogue et une gestion de produits.', approach: 'PHP orienté objet, PDO et MySQL.', results: 'Un projet fondateur dans mon parcours de développement web.' },
  { category: 'WEB', title: 'POST-IT', summary: 'Application monopage permettant de créer et gérer des post-it virtuels.', tags: ['JavaScript', 'SPA', 'API externe'], visual: 'ads', mark: 'SPA', problem: 'Créer une interface simple pour centraliser et gérer des activités sous forme de post-it virtuels.', approach: 'Application monopage en JavaScript connectée à une API externe.', results: 'Fonctionnalités : création et gestion de post-it virtuels.', demo: 'https://fastidious-frangollo-b44eda.netlify.app/', demoLabel: 'Voir la démo ↗' }
]
const projectOrder = ['Sentiment Analysis Pipeline', 'Malaria & Climate Data', 'Book Recommendation System', 'Exploratory Data Analysis', 'POST-IT', 'YOWL', 'FreeAds', 'MyShop']
projects.sort((a, b) => projectOrder.indexOf(a.title) - projectOrder.indexOf(b.title))
projects.forEach((project, index) => { project.number = String(index + 1).padStart(2, '0') })
const filteredProjects = computed(() => activeFilter.value === 'TOUT' ? projects : projects.filter(project => project.category === activeFilter.value))
const buildSteps = ['COLLECTER', 'NETTOYER', 'EXPLORER', 'VISUALISER', 'MODÉLISER', 'DÉPLOYER']
const form = reactive({ name: '', email: '', message: '' })
const sendMessage = () => { location.href = `mailto:samson.kouame@epitech.eu?subject=${encodeURIComponent('Portfolio — ' + form.name)}&body=${encodeURIComponent(form.message + '\n\n— ' + form.name + ' (' + form.email + ')')}` }
</script>
